## By default, Lambda functions have permission to create (Allow logs:CreateLogStream) and write (Allow logs:PutLogEvents) to CloudWatch logs.
## When VPC configuration is provided the default AWS AWSLambdaVPCAccessExecutionRole will be associated to communicate with your VPC resources.
## See https://serverless.com/framework/docs/providers/aws/guide/iam
##

service: serverless

plugins:
  - serverless-finch

custom:
  environment: ${opt:environment, 'dev'}
  region: ${opt:region, 'us-east-1'}
  client:
    bucketName: ${self:custom.environment}.delayediranianapplications.com
    distributionFolder: client/build
    indexDocument: index.html
    errorDocument: error.html

package:
  individually: true
  exclude:
    - ./**
  include:
    - functions/node_modules/**

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${opt:profile}
  region: ${self:custom.region}
  stage: ${self:custom.environment}
  environment:
    ENVIRONMENT: ${self:custom.environment}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:s3:::*
        - arn:aws:dynamodb:${self:custom.region}:*:*

functions:
  message:
    name: ${self:custom.environment}-message
    description: responds to v1/message endpoint
    handler: functions/api/v1/message/index.handler
    timeout: 4
    package:
      include:
        - functions/api/v1/message/**
    events:
      - http:
          path: v1/message
          method: get
          cors: true

resources:
  Resources:
    messagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messagesTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
